# MIT License

# Copyright (c) 2020 Hongrui Zheng

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3'
services:
  sim:
    image: f1tenth_gym_ros
    volumes: 
      - .:/sim_ws/src/f1tenth_gym_ros
      - /Users/joshuaernest/Desktop/Docker/lab-4-follow-the-gap-team_06:/sim_ws/src/lab4
      - /Users/joshuaernest/Desktop/Docker/lab-3-wall-following-team_06:/sim_ws/src/lab3
      - /Users/joshuaernest/Desktop/Docker/lab-5-scan-matching-team_06:/sim_ws/src/lab5
      - /Users/joshuaernest/Desktop/Docker/lab6-slam-and-pure-pursuit-team_06:/sim_ws/src/lab6
      - /Users/joshuaernest/Desktop/Docker/lab-7-motion-planning-team_06:/sim_ws/src/lab7
      - /Users/joshuaernest/Desktop/Docker/lab-8-vision-lab-team_06:/sim_ws/src/lab8
      - /Users/joshuaernest/Desktop/Docker/615Race3Stack:/sim_ws/src/615Race3Stack
      - /Users/joshuaernest/Desktop/Docker/apriltag_ros:/sim_ws/src/apriltag_ros
      - /Users/joshuaernest/Desktop/Docker/apriltag_msgs:/sim_ws/src/apriltag_msgs
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
    stdin_open: true
    tty: true 
  novnc:  
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1728
      - DISPLAY_HEIGHT=972
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11: